### ISSUE TITLE
Making a rocketchat for us

### ISSUE THREAD

**Issue by faddat** [MSF-Jarvis/AAC-Redux#2]
'cause fuck slack.  

I kinda run a somewhat substantial web platform for OSS web apps, is there anything else that I can toss up to ease our collaboration?  I would very much like to grow the scale/scope of this project.

Also, I just got her going.  This is fucking hot.  I also like that you've got it structured so that the user can't help but understand the build process.  

 * Good call on the "only doing Ubuntu for now"; it is the logical choice for the vagrant build system.  
 * Should have the script detect how many cores the CPU has and build using make -j x or (x)2 
 * Sources should sync -j 20 first pass, and second pass at (no -j value, means 4 simultaneous jobs)
 *

**Comment by MSF-Jarvis** [comment]
I think an IRC channel is the most we'll ever need. Will let you know if AAC-Redux.github.io would be required.

1. It is much easier to be able to see errors hands-on rather than quoted by someone else, so first let's finish for Ubuntu.
2. Running a grep on /proc/cpuinfo should work, but I'll need @Paget96 to help me coz he's a wiz with shell.
3. We're better off giving that choice to the user rather than forcing -j 20 ourselves. Will put up a text input asking this when I get back home.

**Comment by faddat** [comment]
ah-- I'm going to give you SSH & a desktop on the machine....

As regards sticking with Ubuntu, yes-- definitley.  It's a stable base.  When I do containers / virtualbox, we'll use Ubuntu in the containers / VM.  Please meet @mhtranbn, another member of the Klouds team and in fact the guy who just ran out to buy us a testbed Nexus 5 (and argued the seller down $20 in the process).

**Comment by MSF-Jarvis** [comment]
Cool. I'll meet him, just send me his email, we'll hook up on Hangouts. And the Nexus 5 is the perfect test device since all ROMs support it so we can do test builds very easily
