### ISSUE TITLE
Updater Required

### ISSUE THREAD

**Issue by MSF-Jarvis** [MSF-Jarvis/AAC-Redux#3]
We need to add a method to be able to allow users to update the application straight from the app itself. I've got an idea but will have to check if it works. If it does, its coming straight up here

**Comment by faddat** [comment]
Let me make sure I understand what you're saying, you are talking about users pushing their modifications back to the repository, correct? Or are you talking about users pulling down changes from the repository? Or are we talking about both? Because actually I think you're talking about the first one of these and I think it's brilliant that would enable our users to remix roms much more easily.

**Comment by MSF-Jarvis** [comment]
Well actually I was talking about the second one, but I'm currently writing a guide to add ROMs to AAC-Redux. Will probably commit it today

**Comment by faddat** [comment]
Can you please add myself and @mhtranbn to this repo as contributors?  Hoang is a member of the Klouds team and will be contributing to AAC :).

**Comment by MSF-Jarvis** [comment]
Hang on, doing in just a minute.

**Comment by MSF-Jarvis** [comment]
Done.

P.S. You were already on the contributors list @faddat, probably you didn't notice. And welcome to the gang @mhtranbn.
